[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
bytecode_hash = 'none'
cbor_metadata = false
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
script = "script"

test = 'test'
cache_path  = 'cache'


[rpc_endpoints]



