[book]
src = "src"
title = ""

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
git-repository-url = "https://cardpay-test.com/git@gitlab.stablecoin/unlimit-defi"

[output.html.fold]
enable = true
